# This file configures the plugins
modules:
  api:
    config:
      port: 8082
    security:
      bearerToken: "change-me"
    endpoints:
      base: "/api"
      serverInfo:
        enabled: true,
        path: "/info"
      consoleCommand:
        enabled: true
        path: "/execute"
      validateRegistration:
        enabled: true
        path: "/validate-registration"
      player:
        enabled: true
        path: "/players"
  mailbox:
    config:
      inventory:
        base: "Mailbox of "
      menus:
        mailboxMenu2:
          maxPages: 10