name: Edwige
version: '1.0-SNAPSHOT'
main: io.realmit.edwige.Main
api-version: '1.21'
load: POSTWORLD
softdepend: [Vault]

commands:
  redeem:
    description: Redeem items
    usage: /redeem
    permission: edwige.command.redeem
  mailbox:
    description: Open/Close player's mailbox
    usage: /mailbox
    permission: edwige.command.mailbox

permissions:
  edwige.command.redeem:
    description: Allows using /edwige:redeem
    default: true
  edwige.command.mailbox:
    description: Allows using /edwige:mailbox
    default: true
